name: Deploy MultiDocker
on:
    push:
        branches:
            - main # check your repo, your default branch might be master!

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - run: docker build -t atul711/react-test -f ./client/Dockerfile.dev ./client
            - run: docker run -e CI=true atul711/react-test npm test

            - run: docker build -t atul711/multi-client ./client
            - run: docker build -t atul711/multi-nginx ./nginx
            - run: docker build -t atul711/multi-server ./server
            - run: docker build -t atul711/multi-worker ./worker

            - run: docker push atul711/multi-client
            - run: docker push atul711/multi-nginx
            - run: docker push atul711/multi-server
            - run: docker push atul711/multi-worker
